---
driver:
  name: ec2
  aws_ssh_key_id: N_Virginia_filatko
  region: us-east-1
  availability_zone: a
  subnet_id: subnet-a1843a8e
  instance_type: t2.micro
  image_id: ami-c29e1cb8
  security_group_ids: ["sg-bf5d52ca"]
  retryable_tries: 120

provisioner:
  name: chef_zero

verifier:
  name: inspec

transport:
  ssh_key: /home/kfilatau/EPAM/LEARN/Amazon/keys/N_Virginia_filatko.pem

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[learn_chef_apache2::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
